name: Testing Github Actions
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ip-10-0-1-200
    steps:
      - name: Building the code
        run : echo $HOSTNAME
