name: Testing Github Actions
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Building the code
        run : echo "Building the code"
